### ISSUE TITLE
Error when trying to set song title in demo

### ISSUE THREAD

**Issue by hopkuba** [satcar77/miband4#43]
When I try to use song title function it throws this error

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/cursesmenu/curses_menu.py", line 133, in _wrap_start
    curses.wrapper(self._main_loop)
  File "/usr/lib/python3.7/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/pi/.local/lib/python3.7/site-packages/cursesmenu/curses_menu.py", line 193, in _main_loop
    self.process_user_input()
  File "/home/pi/.local/lib/python3.7/site-packages/cursesmenu/curses_menu.py", line 289, in process_user_input
    self.select()
  File "/home/pi/.local/lib/python3.7/site-packages/cursesmenu/curses_menu.py", line 329, in select
    self.selected_item.action()
  File "/home/pi/.local/lib/python3.7/site-packages/cursesmenu/items/function_item.py", line 35, in action
    self.return_value = self.function(*self.args, **self.kwargs)
  File "miband4_console.py", line 169, in set_music
    band.setTrack(fi, MUSICSTATE.PLAYED)
  File "/home/pi/miband/miband4/miband.py", line 574, in setTrack
    self.setMusic()
  File "/home/pi/miband/miband4/miband.py", line 623, in setMusic
    buf += self.artist.encode('utf-8') + null
AttributeError: 'int' object has no attribute 'encode'
`
I think that this is lib side error but how to fix it?

**Comment by hopkuba** [comment]
There is easy fix for it, in demo program. Replace function set_music() with this. It prevents hanging MiBand 4 when loading music data and allows to test full capabilities of this part of lib.
```
def set_music(): 
    band.setMusicCallback(_default_music_play,_default_music_pause,_default_music_forward,_default_music_back,_default_music_vup,_default_music_vdown,_default_music_focus_in,_default_music_focus_out)
    fi = input("Set music track artist to : ")
    fj = input("Set music track album to: ")
    fk = input("Set music track title to: ")
    fl = int(input("Set music volume: "))
    fm = int(input("Set music position: "))
    fn = int(input("Set music duration: "))
    band.setTrack(MUSICSTATE.PLAYED,fi,fj,fk,fl,fm,fn)
    while True:
        if band.waitForNotifications(0.5):
            continue
    input("enter any key")
```
