### ISSUE TITLE
Mi band 6 support

### ISSUE THREAD

**Issue by NeptunePy** [satcar77/miband4#52]
I have problems with the mi band 6, can you add support for the mi band 6 please?

Thanks.

**Comment by janvda** [comment]
@Flodr can you provide more details about the issue you are having with mi band 6 ?

**Comment by Flodr** [comment]
Hello, with the mi band 6, none of the available options work, for example the first option shows this:

![image](https://user-images.githubusercontent.com/55653659/146739123-74089dbf-72f3-452d-bed7-489c8f7d40c7.png)


sorry for the late response.

_os : Linux Mint_

**Comment by niceboygithub** [comment]
Testing on Mi Band 6 NFC.

the logs:
```
Connection to the MIBand failed.[1832778.847593] rtk_btcoex: process disconn complete event.
 Trying out again in 3 seconds
[1832778.856038] rtk_btcoex: update_profile_connection: is_add 0, profile_index 1
[1832778.866286] rtk_btcoex: update_profile_connection: btrtl_coex.profile_refcount[1] = 0
[1832778.874551] rtk_btcoex: update_profile_connection: btrtl_coex.profile_bitmap 0x00
[1832778.882429] rtk_btcoex: update_profile_connection: btrtl_coex.profile_refcount[0] = 0
[1832778.890669] rtk_btcoex: update_profile_connection: btrtl_coex.profile_refcount[1] = 0
[1832778.898892] rtk_btcoex: update_profile_connection: btrtl_coex.profile_refcount[2] = 0
[1832778.907114] rtk_btcoex: update_profile_connection: btrtl_coex.profile_refcount[3] = 0
[1832778.915355] rtk_btcoex: update_profile_connection: btrtl_coex.profile_refcount[4] = 0
[1832778.917772] rtk_btusb: btusb_notify: hci0 evt 2
[1832778.928415] rtk_btcoex: update_profile_connection: btrtl_coex.profile_refcount[5] = 0
[1832778.936646] rtk_btcoex: update_profile_connection: btrtl_coex.profile_refcount[6] = 0
[1832778.944968] rtk_btcoex: update_profile_connection: btrtl_coex.profile_refcount[7] = 0
[1832778.953201] rtk_btcoex: rtk_notify_profileinfo_to_fw: BufferSize 2
[1832778.959733] rtk_btcoex: rtk_notify_profileinfo_to_fw: NumberOfHandles 0
[1832778.966707] rtk_btcoex: rtk_notify_profileinfo_to_fw: profile_status 0x00
[1832778.973863] rtk_btcoex: rtk_vendor_cmd_to_fw: opcode 0xfc19
2022-01-19 17:07:04,403 miband (INFO) > Connecting to 11:50:33:4D:66:99
[1832781.863763] rtk_btusb: btusb_notify: hci0 evt 1
[1832787.157860] rtk_btcoex: LE connected, handle 0010, status 0x00, interval 54
[1832787.165343] rtk_btcoex: update_profile_connection: is_add 1, profile_index 1
[1832787.172834] rtk_btcoex: update_profile_connection: btrtl_coex.profile_bitmap 0x02
[1832787.180718] rtk_btcoex: update_profile_connection: btrtl_coex.profile_refcount[0] = 0
[1832787.188975] rtk_btcoex: update_profile_connection: btrtl_coex.profile_refcount[1] = 1
[1832787.197204] rtk_btcoex: update_profile_connection: btrtl_coex.profile_refcount[2] = 0
[1832787.205478] rtk_btcoex: update_profile_connection: btrtl_coex.profile_refcount[3] = 0
[1832787.213726] rtk_btcoex: update_profile_connection: btrtl_coex.profile_refcount[4] = 0
[1832787.221951] rtk_btcoex: update_profile_connection: btrtl_coex.profile_refcount[5] = 0
[1832787.230160] rtk_btcoex: update_profile_connection: btrtl_coex.profile_refcount[6] = 0
[1832787.238379] rtk_btcoex: update_profile_connection: btrtl_coex.profile_refcount[7] = 0
[1832787.246589] rtk_btcoex: rtk_notify_profileinfo_to_fw: BufferSize 5
[1832787.253117] rtk_btcoex: rtk_notify_profileinfo_to_fw: NumberOfHandles 1
[1832787.260082] rtk_btcoex: rtk_notify_profileinfo_to_fw: handle 0x0010
[1832787.266695] rtk_btcoex: rtk_notify_profileinfo_to_fw: profile_bitmap 0x02
[1832787.273837] rtk_btcoex: rtk_notify_profileinfo_to_fw: profile_status 0x00
[1832787.280988] rtk_btcoex: rtk_vendor_cmd_to_fw: opcode 0xfc19
[1832787.286898] rtk_btcoex: update_hid_active_state: handle 0x0010, interval 54
[1832787.294308] rtk_btcoex: rtk_notify_profileinfo_to_fw: BufferSize 5
[1832787.300840] rtk_btcoex: rtk_notify_profileinfo_to_fw: NumberOfHandles 1
[1832787.307815] rtk_btcoex: rtk_notify_profileinfo_to_fw: handle 0x0010
[1832787.314430] rtk_btcoex: rtk_notify_profileinfo_to_fw: profile_bitmap 0x12
[1832787.321577] rtk_btcoex: rtk_notify_profileinfo_to_fw: profile_status 0x02
[1832787.328732] rtk_btcoex: rtk_vendor_cmd_to_fw: opcode 0xfc19
[1832787.530890] rtk_btcoex: disconn cmpl evt: status 0x00, handle 0010, reason 0x3e
Connection to the MIBand failed.[1832787.538613] rtk_btcoex: process disconn complete event.
 Trying out again in 3 seconds
```

**Comment by radu022003** [comment]
> Testing on Mi Band 6 NFC with raspberry pi 3.
> 
> the command:
> 
> ```
> python3 miband4_console.py -m 11:50:33:4D:66:997 -k C11D22D8F33449DDC55686FE3F8C9EAB
> ```
> 
> the logs:
> 
> ```
> Exception in thread Thread-1:o be displayed: test
> Traceback (most recent call last): characters per line, and up to 6 lines. To add a new line use new line character
>   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
>     self.run() message to be displayed: message test
>   File "/usr/lib/python3.7/threading.py", line 865, in runl: 2
>     self._target(*self._args, **self._kwargs)
>   File "/home/pi/.local/lib/python3.7/site-packages/cursesmenu/curses_menu.py", line 133, in _wrap_start
>     curses.wrapper(self._main_loop)
>   File "/usr/lib/python3.7/curses/__init__.py", line 94, in wrapper
>     return func(stdscr, *args, **kwds)
>   File "/home/pi/.local/lib/python3.7/site-packages/cursesmenu/curses_menu.py", line 193, in _main_loop
>     self.process_user_input()
>   File "/home/pi/.local/lib/python3.7/site-packages/cursesmenu/curses_menu.py", line 289, in process_user_input
>     self.select()
>   File "/home/pi/.local/lib/python3.7/site-packages/cursesmenu/curses_menu.py", line 329, in select
>     self.selected_item.action()
>   File "/home/pi/.local/lib/python3.7/site-packages/cursesmenu/items/function_item.py", line 35, in action
>     self.return_value = self.function(*self.args, **self.kwargs)
>   File "miband4_console.py", line 109, in send_notif
>     band.send_custom_alert(a[ty-1],title,msg)
>   File "/home/pi/miband4/miband.py", line 305, in send_custom_alert
>     svc = self.getServiceByUUID(UUIDS.SERVICE_ALERT_NOTIFICATION)
>   File "/home/pi/.local/lib/python3.7/site-packages/bluepy/btle.py", line 488, in getServiceByUUID
>     rsp = self._getResp('find')
>   File "/home/pi/.local/lib/python3.7/site-packages/bluepy/btle.py", line 407, in _getResp
>     resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
>   File "/home/pi/.local/lib/python3.7/site-packages/bluepy/btle.py", line 362, in _waitResp
>     raise BTLEDisconnectError("Device disconnected", resp)
> bluepy.btle.BTLEDisconnectError: Device disconnected
> ```

I am experiencing the same.
I would gladly help to solve the problem if needed.
